# Generated by Django 6.0.7 on 2026-08-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
