# Generated by Django 6.0.7 on 2026-08-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_resumeparse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('match_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='accounts.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_scores', to='accounts.job')),
            ],
            options={
                'ordering': ['-match_percentage'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_ats_score')],
            },
        ),
    ]
