# Generated by Django 6.0.7 on 2026-08-19 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_atsscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsscore',
            name='matched_skill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApplicationResumeParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_parse', to='accounts.application')),
            ],
        ),
    ]
