# Generated by Django 6.0.7 on 2026-08-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
