# Generated by Django 6.0.7 on 2026-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_emaillog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={},
        ),
        migrations.AddField(
            model_name='emaillog',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
