# Generated by Django 6.0.7 on 2026-08-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_emaillog_options_emaillog_context'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['candidate', '-created_at'], name='notif_candidate_created_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['candidate', '-saved_at'], name='savedjob_candidate_saved_idx'),
        ),
    ]
