# Generated by Django 6.0.7 on 2026-09-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_aiinterviewconfig_aicall_interviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.aicall')),
            ],
            options={
                'ordering': ['question_order'],
                'constraints': [models.UniqueConstraint(fields=('ai_call', 'question_order'), name='unique_ai_call_question_order')],
            },
        ),
    ]
