# Generated by Django 6.0.7 on 2026-09-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_aiinterviewanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('summary', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=100)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_report', to='accounts.aicall')),
            ],
        ),
    ]
