# Generated by Django 6.0.7 on 2026-09-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_aiscreeningreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Started', max_length=30)),
                ('transcript', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='accounts.aicall')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CALL_CREATED', 'Call Created'), ('CALL_STARTED', 'Call Started'), ('QUESTION_ASKED', 'Question Asked'), ('ANSWER_RECEIVED', 'Answer Received'), ('CALL_COMPLETED', 'Call Completed'), ('CALL_FAILED', 'Call Failed')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.aiinterviewsession')),
            ],
        ),
    ]
