# Generated by Django 6.0.7 on 2026-09-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('Introduction', 'Introduction'), ('Experience', 'Experience'), ('Skills', 'Skills'), ('Availability', 'Availability'), ('Salary', 'Salary')], max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AIQuestionJobMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_question_mappings', to='accounts.job')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_mappings', to='accounts.aiquestiontemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question', 'job'), name='unique_ai_question_job_mapping')],
            },
        ),
    ]
