# Generated by Django 6.0.7 on 2026-09-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_aiquestiontemplate_aiquestionjobmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completeness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='accounts.aiinterviewanswer')),
            ],
        ),
    ]
