# Generated by Django 6.0.7 on 2026-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_candidateinterviewavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_interview_duration',
            field=models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=30),
        ),
    ]
