# Generated by Django 6.0.7 on 2026-09-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_job_ai_interview_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24_HOURS', '24 Hours Before'), ('1_HOUR', '1 Hour Before')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('interview_scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_reminder', to='accounts.emaillog')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.interviewschedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('interview', 'reminder_type', 'interview_scheduled_at'), name='unique_interview_reminder')],
            },
        ),
    ]
