# Generated by Django 6.0.7 on 2026-09-24 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_interviewreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICandidateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_call_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_candidate_report', to='accounts.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
