# Generated by Django 6.0.7 on 2026-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_aicandidatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('AI', 'AI'), ('SYSTEM', 'System'), ('SECURITY', 'Security')], default='ADMIN', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
