# Generated by Django 6.0.7 on 2026-09-28 05:07

import accounts.services.encrypted_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auditlog_actor_type_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=accounts.services.encrypted_field.EncryptedTextField(blank=True, null=True),
        ),
    ]
