# Generated by Django 6.0.7 on 2026-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_subscriptionplan_usersubscription_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Feature entitlements available for this plan.'),
        ),
    ]
