# Generated by Django 6.0.7 on 2026-10-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='accounts.subscriptionplan'),
            preserve_default=False,
        ),
    ]
