# Generated by Django 6.0.7 on 2026-10-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_paymenttransaction_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
