# Generated by Django 6.0.7 on 2026-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_paymenttransaction_gateway_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
