# Generated by Django 6.0.7 on 2026-10-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_usersubscription_grace_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='candidate_access_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum candidates accessible per billing period. Null means unlimited.', null=True),
        ),
    ]
