# Generated by Django 6.0.7 on 2026-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_subscriptionplan_candidate_access_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
