# Generated by Django 6.0.7 on 2026-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_scheduledinterviewquestion_scheduledinterviewanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreminder',
            name='reminder_type',
            field=models.CharField(choices=[('24_HOURS', '24 Hours Before'), ('1_HOUR', '1 Hour Before'), ('AT_TIME', 'At Interview Time')], max_length=20),
        ),
    ]
