# Generated by Django 6.0.7 on 2026-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_interviewreminder_reminder_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aicall',
            index=models.Index(fields=['status', 'scheduled_at'], name='aicall_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='aicall',
            index=models.Index(fields=['status', 'next_retry_at'], name='aicall_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewreminder',
            index=models.Index(fields=['status', 'scheduled_for'], name='reminder_due_idx'),
        ),
    ]
